// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RedDiff.Infraestructura.Persistencia;

#nullable disable

namespace RedDiff.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoRedDiff))]
    partial class ContextoRedDiffModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reddiff")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.Captura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("captura_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Disparador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("disparador");

                    b.Property<long>("DispositivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispositivo_id");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<long?>("EventoCambioId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Medio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("protocolo");

                    b.Property<long?>("UsuarioSolicitanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_captura");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_captura_estado");

                    b.HasIndex("EventoCambioId")
                        .IsUnique()
                        .HasDatabaseName("ux_captura_evento");

                    b.HasIndex("UsuarioSolicitanteId")
                        .HasDatabaseName("ix_captura_usuario");

                    b.HasIndex("DispositivoId", "Fecha")
                        .HasDatabaseName("ix_captura_dispositivo_fecha");

                    b.HasIndex("DispositivoId", "Disparador", "Fecha")
                        .HasDatabaseName("ix_captura_dispositivo_disparador_fecha");

                    b.ToTable("captura", "reddiff", t =>
                        {
                            t.HasCheckConstraint("ck_captura_origen", "(disparador = 'BajoDemanda' AND usuario_id IS NOT NULL AND evento_id IS NULL) OR (disparador = 'Evento' AND usuario_id IS NULL AND evento_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.EventoCambio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContenidoEvento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido_evento");

                    b.Property<long>("DispositivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispositivo_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fuente");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("huella");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_evento_cambio");

                    b.HasIndex("DispositivoId", "Huella")
                        .IsUnique()
                        .HasDatabaseName("ux_evento_cambio_dispositivo_huella");

                    b.HasIndex("Estado", "Fecha")
                        .HasDatabaseName("ix_evento_cambio_estado_fecha");

                    b.ToTable("evento_cambio", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CapturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("captura_id");

                    b.Property<DateTimeOffset>("CapturadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturada_en");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comentario");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<long>("DispositivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispositivo_id");

                    b.Property<bool>("Estable")
                        .HasColumnType("boolean")
                        .HasColumnName("estable");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("hash");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origen");

                    b.Property<DateTimeOffset?>("ValidadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validada_en");

                    b.Property<long?>("ValidadaPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("validada_por_usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_version_config");

                    b.HasIndex("CapturaId")
                        .IsUnique()
                        .HasDatabaseName("ux_version_config_captura");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_version_config_hash");

                    b.HasIndex("ValidadaPorUsuarioId")
                        .HasDatabaseName("ix_version_config_usuario_validador");

                    b.HasIndex("DispositivoId", "CapturadaEn")
                        .HasDatabaseName("ix_version_config_dispositivo_fecha");

                    b.HasIndex("DispositivoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_version_config_dispositivo_numero");

                    b.HasIndex("DispositivoId", "Estado", "CapturadaEn")
                        .HasDatabaseName("ix_version_config_dispositivo_estado_fecha");

                    b.HasIndex("DispositivoId", "Origen", "CapturadaEn")
                        .HasDatabaseName("ix_version_config_dispositivo_origen_fecha");

                    b.ToTable("version_config", "reddiff", t =>
                        {
                            t.HasCheckConstraint("ck_version_config_estable", "(estable = FALSE AND validada_por_usuario_id IS NULL AND validada_en IS NULL) OR (estable = TRUE AND validada_por_usuario_id IS NOT NULL AND validada_en IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Comparaciones.Comparacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("comparacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<long>("VersionDestinoId")
                        .HasColumnType("bigint")
                        .HasColumnName("version_destino_id");

                    b.Property<long>("VersionOrigenId")
                        .HasColumnType("bigint")
                        .HasColumnName("version_origen_id");

                    b.HasKey("Id")
                        .HasName("pk_comparacion");

                    b.HasIndex("VersionDestinoId")
                        .HasDatabaseName("ix_comparacion_version_destino");

                    b.HasIndex("UsuarioId", "Fecha")
                        .HasDatabaseName("ix_comparacion_usuario_fecha");

                    b.HasIndex("VersionOrigenId", "VersionDestinoId", "Fecha")
                        .HasDatabaseName("ix_comparacion_versiones_fecha");

                    b.ToTable("comparacion", "reddiff", t =>
                        {
                            t.HasCheckConstraint("ck_comparacion_versiones_diferentes", "version_origen_id <> version_destino_id");
                        });
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Comparaciones.DetalleDiferencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("diferencia_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComparacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("comparacion_id");

                    b.Property<int>("Linea")
                        .HasColumnType("integer")
                        .HasColumnName("linea");

                    b.Property<string>("TextoAnterior")
                        .HasColumnType("text")
                        .HasColumnName("texto_anterior");

                    b.Property<string>("TextoNuevo")
                        .HasColumnType("text")
                        .HasColumnName("texto_nuevo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_detalle_diferencia");

                    b.HasIndex("ComparacionId", "Linea")
                        .HasDatabaseName("ix_detalle_diferencia_comparacion_linea");

                    b.ToTable("detalle_diferencia", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.Baseline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("baseline_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<long?>("DispositivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispositivo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoDispositivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_dispositivo");

                    b.Property<long?>("VersionReferenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_baseline");

                    b.HasIndex("VersionReferenciaId")
                        .HasDatabaseName("ix_baseline_version_config");

                    b.HasIndex("DispositivoId", "Activa")
                        .HasDatabaseName("ix_baseline_dispositivo_activa");

                    b.HasIndex("TipoDispositivo", "Activa")
                        .HasDatabaseName("ix_baseline_tipo_activa");

                    b.ToTable("baseline", "reddiff", t =>
                        {
                            t.HasCheckConstraint("ck_baseline_destino", "(dispositivo_id IS NOT NULL AND tipo_dispositivo IS NULL) OR (dispositivo_id IS NULL AND tipo_dispositivo IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.ReglaBaseline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("regla_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BaselineId")
                        .HasColumnType("bigint")
                        .HasColumnName("baseline_id");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("criterio");

                    b.Property<string>("Esperado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("esperado");

                    b.Property<bool>("Obligatoria")
                        .HasColumnType("boolean")
                        .HasColumnName("obligatorio");

                    b.HasKey("Id")
                        .HasName("pk_regla_baseline");

                    b.HasIndex("BaselineId")
                        .HasDatabaseName("ix_regla_baseline_baseline");

                    b.ToTable("regla_baseline", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.ResultadoRegla", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("resultado_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<string>("Evidencia")
                        .HasColumnType("text")
                        .HasColumnName("evidencia");

                    b.Property<long>("ReglaId")
                        .HasColumnType("bigint")
                        .HasColumnName("regla_id");

                    b.Property<long>("VerificacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("verificacion_id");

                    b.HasKey("Id")
                        .HasName("pk_resultado_regla");

                    b.HasIndex("ReglaId")
                        .HasDatabaseName("ix_resultado_regla_regla_baseline");

                    b.HasIndex("VerificacionId", "ReglaId")
                        .IsUnique()
                        .HasDatabaseName("ux_resultado_regla_verificacion_regla");

                    b.ToTable("resultado_regla", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.Verificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("verificacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BaselineId")
                        .HasColumnType("bigint")
                        .HasColumnName("baseline_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_verificacion");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("ix_verificacion_version_config");

                    b.HasIndex("UsuarioId", "Fecha")
                        .HasDatabaseName("ix_verificacion_usuario_fecha");

                    b.HasIndex("BaselineId", "VersionId", "Fecha")
                        .HasDatabaseName("ix_verificacion_baseline_version_fecha");

                    b.ToTable("verificacion", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Identidad.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rol");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_rol_nombre");

                    b.ToTable("rol", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Identidad.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("contrasena_hash");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_nombre");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_rol");

                    b.ToTable("usuario", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Inventario.Dispositivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dispositivo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<string>("FuenteEventos")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fuente_eventos");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<string>("Modelo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modelo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocolo");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer")
                        .HasColumnName("puerto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_dispositivo");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_dispositivo_nombre");

                    b.HasIndex("Host", "Puerto")
                        .IsUnique()
                        .HasDatabaseName("ux_dispositivo_host_puerto");

                    b.ToTable("dispositivo", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Trazabilidad.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("auditoria_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entidad");

                    b.Property<long?>("EntidadId")
                        .HasColumnType("bigint")
                        .HasColumnName("entidad_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_auditoria_fecha");

                    b.HasIndex("UsuarioId", "Fecha")
                        .HasDatabaseName("ix_auditoria_usuario_fecha");

                    b.HasIndex("Entidad", "EntidadId", "Fecha")
                        .HasDatabaseName("ix_auditoria_entidad_fecha");

                    b.ToTable("auditoria", "reddiff");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.Captura", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Inventario.Dispositivo", "Dispositivo")
                        .WithMany("Capturas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_captura_dispositivo");

                    b.HasOne("RedDiff.Dominio.Entidades.Capturas.EventoCambio", "EventoCambio")
                        .WithOne("Captura")
                        .HasForeignKey("RedDiff.Dominio.Entidades.Capturas.Captura", "EventoCambioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_captura_evento_cambio");

                    b.HasOne("RedDiff.Dominio.Entidades.Identidad.Usuario", "UsuarioSolicitante")
                        .WithMany("CapturasSolicitadas")
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_captura_usuario");

                    b.Navigation("Dispositivo");

                    b.Navigation("EventoCambio");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.EventoCambio", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Inventario.Dispositivo", "Dispositivo")
                        .WithMany("EventosCambio")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evento_cambio_dispositivo");

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Capturas.Captura", "Captura")
                        .WithOne("VersionConfiguracion")
                        .HasForeignKey("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", "CapturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_version_config_captura");

                    b.HasOne("RedDiff.Dominio.Entidades.Inventario.Dispositivo", "Dispositivo")
                        .WithMany("VersionesConfiguracion")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_version_config_dispositivo");

                    b.HasOne("RedDiff.Dominio.Entidades.Identidad.Usuario", "ValidadaPorUsuario")
                        .WithMany("VersionesValidadas")
                        .HasForeignKey("ValidadaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_version_config_usuario_validador");

                    b.Navigation("Captura");

                    b.Navigation("Dispositivo");

                    b.Navigation("ValidadaPorUsuario");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Comparaciones.Comparacion", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Identidad.Usuario", "Usuario")
                        .WithMany("Comparaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparacion_usuario");

                    b.HasOne("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", "VersionDestino")
                        .WithMany("ComparacionesDestino")
                        .HasForeignKey("VersionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparacion_version_destino");

                    b.HasOne("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", "VersionOrigen")
                        .WithMany("ComparacionesOrigen")
                        .HasForeignKey("VersionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparacion_version_origen");

                    b.Navigation("Usuario");

                    b.Navigation("VersionDestino");

                    b.Navigation("VersionOrigen");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Comparaciones.DetalleDiferencia", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Comparaciones.Comparacion", "Comparacion")
                        .WithMany("Diferencias")
                        .HasForeignKey("ComparacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_diferencia_comparacion");

                    b.Navigation("Comparacion");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.Baseline", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Inventario.Dispositivo", "Dispositivo")
                        .WithMany("Baselines")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_baseline_dispositivo");

                    b.HasOne("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", "VersionReferencia")
                        .WithMany("BaselinesReferencia")
                        .HasForeignKey("VersionReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_baseline_version_config");

                    b.Navigation("Dispositivo");

                    b.Navigation("VersionReferencia");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.ReglaBaseline", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Cumplimiento.Baseline", "Baseline")
                        .WithMany("Reglas")
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_regla_baseline_baseline");

                    b.Navigation("Baseline");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.ResultadoRegla", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Cumplimiento.ReglaBaseline", "Regla")
                        .WithMany("Resultados")
                        .HasForeignKey("ReglaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resultado_regla_regla_baseline");

                    b.HasOne("RedDiff.Dominio.Entidades.Cumplimiento.Verificacion", "Verificacion")
                        .WithMany("Resultados")
                        .HasForeignKey("VerificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resultado_regla_verificacion");

                    b.Navigation("Regla");

                    b.Navigation("Verificacion");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.Verificacion", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Cumplimiento.Baseline", "Baseline")
                        .WithMany("Verificaciones")
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verificacion_baseline");

                    b.HasOne("RedDiff.Dominio.Entidades.Identidad.Usuario", "Usuario")
                        .WithMany("Verificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verificacion_usuario");

                    b.HasOne("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", "Version")
                        .WithMany("Verificaciones")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verificacion_version_config");

                    b.Navigation("Baseline");

                    b.Navigation("Usuario");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Identidad.Usuario", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Identidad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Trazabilidad.Auditoria", b =>
                {
                    b.HasOne("RedDiff.Dominio.Entidades.Identidad.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditoria_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.Captura", b =>
                {
                    b.Navigation("VersionConfiguracion");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.EventoCambio", b =>
                {
                    b.Navigation("Captura");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Capturas.VersionConfiguracion", b =>
                {
                    b.Navigation("BaselinesReferencia");

                    b.Navigation("ComparacionesDestino");

                    b.Navigation("ComparacionesOrigen");

                    b.Navigation("Verificaciones");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Comparaciones.Comparacion", b =>
                {
                    b.Navigation("Diferencias");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.Baseline", b =>
                {
                    b.Navigation("Reglas");

                    b.Navigation("Verificaciones");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.ReglaBaseline", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Cumplimiento.Verificacion", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Identidad.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Identidad.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("CapturasSolicitadas");

                    b.Navigation("Comparaciones");

                    b.Navigation("Verificaciones");

                    b.Navigation("VersionesValidadas");
                });

            modelBuilder.Entity("RedDiff.Dominio.Entidades.Inventario.Dispositivo", b =>
                {
                    b.Navigation("Baselines");

                    b.Navigation("Capturas");

                    b.Navigation("EventosCambio");

                    b.Navigation("VersionesConfiguracion");
                });
#pragma warning restore 612, 618
        }
    }
}
