DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'reddiff') THEN
        CREATE SCHEMA reddiff;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS reddiff.__historial_migraciones (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___historial_migraciones" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'reddiff') THEN
            CREATE SCHEMA reddiff;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.dispositivo (
        dispositivo_id bigint GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(120) NOT NULL,
        host character varying(255) NOT NULL,
        tipo character varying(100) NOT NULL,
        modelo character varying(120),
        protocolo character varying(20) NOT NULL,
        puerto integer NOT NULL,
        fuente_eventos character varying(30),
        estado character varying(30) NOT NULL,
        CONSTRAINT pk_dispositivo PRIMARY KEY (dispositivo_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.rol (
        rol_id bigint GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(80) NOT NULL,
        estado boolean NOT NULL,
        CONSTRAINT pk_rol PRIMARY KEY (rol_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.evento_cambio (
        evento_id bigint GENERATED BY DEFAULT AS IDENTITY,
        dispositivo_id bigint NOT NULL,
        fuente character varying(255) NOT NULL,
        tipo character varying(30) NOT NULL,
        fecha timestamp with time zone NOT NULL,
        huella character(64) NOT NULL,
        contenido_evento text NOT NULL,
        estado character varying(30) NOT NULL,
        CONSTRAINT pk_evento_cambio PRIMARY KEY (evento_id),
        CONSTRAINT fk_evento_cambio_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES reddiff.dispositivo (dispositivo_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.usuario (
        usuario_id bigint GENERATED BY DEFAULT AS IDENTITY,
        rol_id bigint NOT NULL,
        usuario character varying(100) NOT NULL,
        contrasena_hash character varying(512) NOT NULL,
        estado boolean NOT NULL,
        CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
        CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES reddiff.rol (rol_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.auditoria (
        auditoria_id bigint GENERATED BY DEFAULT AS IDENTITY,
        usuario_id bigint,
        accion character varying(120) NOT NULL,
        entidad character varying(120) NOT NULL,
        entidad_id bigint,
        fecha timestamp with time zone NOT NULL,
        estado character varying(30) NOT NULL,
        detalle text,
        CONSTRAINT pk_auditoria PRIMARY KEY (auditoria_id),
        CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES reddiff.usuario (usuario_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.captura (
        captura_id bigint GENERATED BY DEFAULT AS IDENTITY,
        dispositivo_id bigint NOT NULL,
        evento_id bigint,
        usuario_id bigint,
        disparador character varying(30) NOT NULL,
        protocolo character varying(30) NOT NULL,
        estado character varying(30) NOT NULL,
        fecha timestamp with time zone NOT NULL,
        error character varying(2000),
        CONSTRAINT pk_captura PRIMARY KEY (captura_id),
        CONSTRAINT ck_captura_origen CHECK ((disparador = 'BajoDemanda' AND usuario_id IS NOT NULL AND evento_id IS NULL) OR (disparador = 'Evento' AND usuario_id IS NULL AND evento_id IS NOT NULL)),
        CONSTRAINT fk_captura_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES reddiff.dispositivo (dispositivo_id) ON DELETE RESTRICT,
        CONSTRAINT fk_captura_evento_cambio FOREIGN KEY (evento_id) REFERENCES reddiff.evento_cambio (evento_id) ON DELETE RESTRICT,
        CONSTRAINT fk_captura_usuario FOREIGN KEY (usuario_id) REFERENCES reddiff.usuario (usuario_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.version_config (
        version_id bigint GENERATED BY DEFAULT AS IDENTITY,
        dispositivo_id bigint NOT NULL,
        captura_id bigint NOT NULL,
        numero integer NOT NULL,
        origen character varying(30) NOT NULL,
        contenido text NOT NULL,
        hash character(64) NOT NULL,
        capturada_en timestamp with time zone NOT NULL,
        comentario character varying(500),
        estado character varying(30) NOT NULL,
        estable boolean NOT NULL,
        validada_por_usuario_id bigint,
        validada_en timestamp with time zone,
        CONSTRAINT pk_version_config PRIMARY KEY (version_id),
        CONSTRAINT ck_version_config_estable CHECK ((estable = FALSE AND validada_por_usuario_id IS NULL AND validada_en IS NULL) OR (estable = TRUE AND validada_por_usuario_id IS NOT NULL AND validada_en IS NOT NULL)),
        CONSTRAINT fk_version_config_captura FOREIGN KEY (captura_id) REFERENCES reddiff.captura (captura_id) ON DELETE RESTRICT,
        CONSTRAINT fk_version_config_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES reddiff.dispositivo (dispositivo_id) ON DELETE RESTRICT,
        CONSTRAINT fk_version_config_usuario_validador FOREIGN KEY (validada_por_usuario_id) REFERENCES reddiff.usuario (usuario_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.baseline (
        baseline_id bigint GENERATED BY DEFAULT AS IDENTITY,
        dispositivo_id bigint,
        tipo_dispositivo character varying(100),
        version_id bigint,
        nombre character varying(150) NOT NULL,
        activa boolean NOT NULL,
        CONSTRAINT pk_baseline PRIMARY KEY (baseline_id),
        CONSTRAINT ck_baseline_destino CHECK ((dispositivo_id IS NOT NULL AND tipo_dispositivo IS NULL) OR (dispositivo_id IS NULL AND tipo_dispositivo IS NOT NULL)),
        CONSTRAINT fk_baseline_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES reddiff.dispositivo (dispositivo_id) ON DELETE RESTRICT,
        CONSTRAINT fk_baseline_version_config FOREIGN KEY (version_id) REFERENCES reddiff.version_config (version_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.comparacion (
        comparacion_id bigint GENERATED BY DEFAULT AS IDENTITY,
        version_origen_id bigint NOT NULL,
        version_destino_id bigint NOT NULL,
        usuario_id bigint NOT NULL,
        fecha timestamp with time zone NOT NULL,
        estado character varying(30) NOT NULL,
        CONSTRAINT pk_comparacion PRIMARY KEY (comparacion_id),
        CONSTRAINT ck_comparacion_versiones_diferentes CHECK (version_origen_id <> version_destino_id),
        CONSTRAINT fk_comparacion_usuario FOREIGN KEY (usuario_id) REFERENCES reddiff.usuario (usuario_id) ON DELETE RESTRICT,
        CONSTRAINT fk_comparacion_version_destino FOREIGN KEY (version_destino_id) REFERENCES reddiff.version_config (version_id) ON DELETE RESTRICT,
        CONSTRAINT fk_comparacion_version_origen FOREIGN KEY (version_origen_id) REFERENCES reddiff.version_config (version_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.regla_baseline (
        regla_id bigint GENERATED BY DEFAULT AS IDENTITY,
        baseline_id bigint NOT NULL,
        criterio character varying(40) NOT NULL,
        esperado text NOT NULL,
        obligatorio boolean NOT NULL,
        CONSTRAINT pk_regla_baseline PRIMARY KEY (regla_id),
        CONSTRAINT fk_regla_baseline_baseline FOREIGN KEY (baseline_id) REFERENCES reddiff.baseline (baseline_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.verificacion (
        verificacion_id bigint GENERATED BY DEFAULT AS IDENTITY,
        baseline_id bigint NOT NULL,
        version_id bigint NOT NULL,
        usuario_id bigint NOT NULL,
        fecha timestamp with time zone NOT NULL,
        estado character varying(30) NOT NULL,
        CONSTRAINT pk_verificacion PRIMARY KEY (verificacion_id),
        CONSTRAINT fk_verificacion_baseline FOREIGN KEY (baseline_id) REFERENCES reddiff.baseline (baseline_id) ON DELETE RESTRICT,
        CONSTRAINT fk_verificacion_usuario FOREIGN KEY (usuario_id) REFERENCES reddiff.usuario (usuario_id) ON DELETE RESTRICT,
        CONSTRAINT fk_verificacion_version_config FOREIGN KEY (version_id) REFERENCES reddiff.version_config (version_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.detalle_diferencia (
        diferencia_id bigint GENERATED BY DEFAULT AS IDENTITY,
        comparacion_id bigint NOT NULL,
        linea integer NOT NULL,
        tipo character varying(30) NOT NULL,
        texto_anterior text,
        texto_nuevo text,
        CONSTRAINT pk_detalle_diferencia PRIMARY KEY (diferencia_id),
        CONSTRAINT fk_detalle_diferencia_comparacion FOREIGN KEY (comparacion_id) REFERENCES reddiff.comparacion (comparacion_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE TABLE reddiff.resultado_regla (
        resultado_id bigint GENERATED BY DEFAULT AS IDENTITY,
        verificacion_id bigint NOT NULL,
        regla_id bigint NOT NULL,
        estado character varying(30) NOT NULL,
        evidencia text,
        CONSTRAINT pk_resultado_regla PRIMARY KEY (resultado_id),
        CONSTRAINT fk_resultado_regla_regla_baseline FOREIGN KEY (regla_id) REFERENCES reddiff.regla_baseline (regla_id) ON DELETE RESTRICT,
        CONSTRAINT fk_resultado_regla_verificacion FOREIGN KEY (verificacion_id) REFERENCES reddiff.verificacion (verificacion_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_auditoria_entidad_fecha ON reddiff.auditoria (entidad, entidad_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_auditoria_fecha ON reddiff.auditoria (fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_auditoria_usuario_fecha ON reddiff.auditoria (usuario_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_baseline_dispositivo_activa ON reddiff.baseline (dispositivo_id, activa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_baseline_tipo_activa ON reddiff.baseline (tipo_dispositivo, activa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_baseline_version_config ON reddiff.baseline (version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_captura_dispositivo_disparador_fecha ON reddiff.captura (dispositivo_id, disparador, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_captura_dispositivo_fecha ON reddiff.captura (dispositivo_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_captura_estado ON reddiff.captura (estado);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_captura_usuario ON reddiff.captura (usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_captura_evento ON reddiff.captura (evento_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_comparacion_usuario_fecha ON reddiff.comparacion (usuario_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_comparacion_version_destino ON reddiff.comparacion (version_destino_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_comparacion_versiones_fecha ON reddiff.comparacion (version_origen_id, version_destino_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_detalle_diferencia_comparacion_linea ON reddiff.detalle_diferencia (comparacion_id, linea);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_dispositivo_host_puerto ON reddiff.dispositivo (host, puerto);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_dispositivo_nombre ON reddiff.dispositivo (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_evento_cambio_estado_fecha ON reddiff.evento_cambio (estado, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_evento_cambio_dispositivo_huella ON reddiff.evento_cambio (dispositivo_id, huella);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_regla_baseline_baseline ON reddiff.regla_baseline (baseline_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_resultado_regla_regla_baseline ON reddiff.resultado_regla (regla_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_resultado_regla_verificacion_regla ON reddiff.resultado_regla (verificacion_id, regla_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_rol_nombre ON reddiff.rol (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_usuario_rol ON reddiff.usuario (rol_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_usuario_nombre ON reddiff.usuario (usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_verificacion_baseline_version_fecha ON reddiff.verificacion (baseline_id, version_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_verificacion_usuario_fecha ON reddiff.verificacion (usuario_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_verificacion_version_config ON reddiff.verificacion (version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_version_config_dispositivo_estado_fecha ON reddiff.version_config (dispositivo_id, estado, capturada_en);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_version_config_dispositivo_fecha ON reddiff.version_config (dispositivo_id, capturada_en);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_version_config_dispositivo_origen_fecha ON reddiff.version_config (dispositivo_id, origen, capturada_en);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_version_config_hash ON reddiff.version_config (hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE INDEX ix_version_config_usuario_validador ON reddiff.version_config (validada_por_usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_version_config_captura ON reddiff.version_config (captura_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    CREATE UNIQUE INDEX ux_version_config_dispositivo_numero ON reddiff.version_config (dispositivo_id, numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM reddiff.__historial_migraciones WHERE "MigrationId" = '20260904032054_Inicial') THEN
    INSERT INTO reddiff.__historial_migraciones ("MigrationId", "ProductVersion")
    VALUES ('20260904032054_Inicial', '10.0.11');
    END IF;
END $EF$;
COMMIT;

